### ISSUE TITLE
Potential Names

### ISSUE THREAD

**Issue by BigglesProject** [HandsomeBoii/nature#11]
Eros Nexus
Eros Connection
Eros Project (Project Eros)

Avalon 
Avanon

**Comment by HandsomeBoii** [comment]
Adding a wide net of potential URLs with prices per year:
avanon.io = 39/yr
avanonline.net = 11/yr 
avanon.me = 17/yr
avanon.plus = 31/yr
avanon.ninja = 18/yr
avanon.online = 39/yr
avanon.co = 25/yr
4vanon.com = 12/yr
avanon.cloud = 23/yr
avanon.tv = 32/yr	
avanonplay.com = 12/yr
