### ISSUE TITLE
Bug Testing

### ISSUE THREAD

**Issue by BigglesProject** [HandsomeBoii/nature#4]

**Comment by BigglesProject** [comment]
Seemed to be unable to post messages with a .gif file type attached.

**Comment by BigglesProject** [comment]
If any image is attached and you spam click post- it will post multiple times. Happened on accident to a beta-tester in multiple instances

**Comment by BigglesProject** [comment]
Player's are unable to do more than one instance of italics. Needs to be fixed so can have multiple paragraphs with italics in one post

**Comment by HandsomeBoii** [comment]
Resolved mentioned bugs.
