### ISSUE TITLE
[Bug] Duplicate Reply Indicators 

### ISSUE THREAD

**Issue by BigglesProject** [HandsomeBoii/nature#40]
![Capture1](https://user-images.githubusercontent.com/62211443/83976600-fd035100-a8c8-11ea-8c9b-90f9c222bd70.PNG)

**Comment by HandsomeBoii** [comment]
Hey this doesnt look like an issue anymore as far as I see, Let me know if this happens in live sessions because looking back at the history, the chat seems fine
